apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-serving-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGDCCAgCgAwIBAgIIWSFg9+MnFbEwDQYJKoZIhvcNAQELBQAwKjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRQwEgYDVQQDEwtldGNkLXNpZ25lcjAeFw0yMTExMDQxNDA2
    MzZaFw0zMTExMDIxNDA2MzZaMCoxEjAQBgNVBAsTCW9wZW5zaGlmdDEUMBIGA1UE
    AxMLZXRjZC1zaWduZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCo
    8l/EdzEOMYFW1sbH2TDHY0nuB+MXvqdfks3QZKKhecnQpgElg+gO7jJKE/OoPdam
    S0/zxsnZSCwI0N55KN8ArGtQd/YbajoyxWHL5FM6+XO+A4TQkZZyE3Y+oFAOp5II
    hLsw2e+PLD1u5Ks0wpI7+00UAEJ4E0Xxj4I/bMwXDDAe/WgTVZsUUix7NJHNBapr
    ErnMUiyZ8TOnrsCKu22xAV5GLVUcSF/8GEXOWsMT9/lL6j1Sb5WVG4w9lXUHThuI
    HecmNAuPMvzxUF5saULadJQ7Y2Va8AqVf9uk1uQFe7mQLQ7ivJ0QSER+uFTLtmVu
    XosjMXsvea1ertIXJU/PAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMB
    Af8EBTADAQH/MB0GA1UdDgQWBBTdID6YS2olijFSoatQatRZG9sTRjANBgkqhkiG
    9w0BAQsFAAOCAQEAiemigLqNHWkIaXJMYbDIBkqBYNHZPAl4EfEPUpEx07FCSfEC
    L+W12QUfchC0kNQmhZYzlwhvk++BcQ1qxoAh8cyMFUXaRPBp6+z+5CpygfdaATYe
    s6ObasyOUiT3qv1xcB3q3vzLEeVuCxx3myA4HrwnGhRSMi2tCota8XVQJdpEoJzR
    VyoR2bztgRkfsse6PTTrFUh9aJ6iy700TolCvLj4eoxAv2+cptycMcGSsx0pGbz9
    4CgdBFAwXK2FxWKywFlNmfKpzDYkGaZSNou24B6zWwE6dugwfH2zFhMOu2IMm7Rl
    uK6Id13wmS1bVzZnAh88rymC0E3qCFRr62gyCw==
    -----END CERTIFICATE-----
    
